@baseUrl = https://so8vy8ckmf.execute-api.eu-central-1.amazonaws.com

###

GET {{baseUrl}}/auctions?status=OPEN

###

GET {{baseUrl}}/auction/uuid

###

POST {{baseUrl}}/auction
Content-Type: application/json

{
	"title": "test auction 1"
}

###

@auctionId = 07c43e1a-9c87-4c78-89da-4aacf9fda0e4
PATCH {{baseUrl}}/auction/{{auctionId}}/bid
Content-Type: application/json

{
	"amount": 16
}

###

curl --request POST \
  --url https://udemy-sls-auction-service.eu.auth0.com/oauth/token \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data client_id=wcw9DyqwT4T3zDc8lGkRvh6DcxuQFWyt \
  --data username=EMAIL_ADDRESS \
  --data 'password=PASSWORD' \
  --data grant_type=password \
  --data scope=openid

###

curl --request POST \
  --url https://26ja4ik8aa.execute-api.eu-central-1.amazonaws.com/dev/private \
  --header 'Authorization: Bearer AUTH0.COM_ID_TOKEN'
